export const modals = {
  PAUSED: 'PAUSED_MODAL',
  LOGIN: 'LOGIN_MODAL',
  SIGNUP: 'SIGNUP_MODAL',
  DOWNLOAD_ERROR: 'DOWNLOAD_ERROR_MODAL',
  PUZZLE_COMPLETED: 'PUZZLE_COMPLETED_MODAL',
  PUZZLE_SOLVED: 'PUZZLE_SOLVED_MODAL'
}