export const modals = {
  PAUSED: 'PAUSED_MODAL',
  LOGIN: 'LOGIN_MODAL',
  SIGNUP: 'SIGNUP_MODAL',
  PROFILE: 'PROFILE_MODAL',
  DOWNLOAD_ERROR: 'DOWNLOAD_ERROR_MODAL',
  PUZZLE_READY: 'PUZZLE_READY',
  PUZZLE_COMPLETED: 'PUZZLE_COMPLETED_MODAL',
  PUZZLE_SOLVED: 'PUZZLE_SOLVED_MODAL',
  CREATE_GAME: 'CREATE_GAME_MODAL'
}