export const gameTypes = {
  CLEAR_GAME_STATE: 'CLEAR_GAME_STATE',
  GAME_REQUEST_INITIATED: 'GAME_REQUEST_INITIATED',
  GAME_REQUEST_FAILED: 'GAME_REQUEST_FAILED',
  GAME_FETCHED: 'GAME_FETCHED',
  GAMES_FETCHED: 'GAMES_FETCHED',
  GAME_CREATED: 'GAME_CREATED',
  GAME_UPDATED: 'GAME_UPDATED',
  GAME_DATA_RECEIVED: 'GAME_DATA_RECEIVED',
  GAME_JOINED: 'GAME_JOINED',
  GAME_PAUSED: 'GAME_PAUSED',
  GAME_UNPAUSED: 'GAME_UNPAUSED',
  LOBBY_UPDATED: 'LOBBY_UPDATED',
  PLAYER_ACTIVE_UPDATED: 'PLAYER_ACTIVE_UPDATED',
  PLAYERS_UPDATED: 'PLAYERS_UPDATED',
  POSITION_UPDATED: 'POSITION_UPDATED',
  GAME_REMOVED: 'GAME_REMOVED'
}