export const gameTypes = {
  GAME_REQUEST_INITIATED: 'GAME_REQUEST_INITIATED',
  GAME_REQUEST_FAILED: 'GAME_REQUEST_FAILED',
  GAME_FETCHED: 'GAME_FETCHED',
  GAMES_FETCHED: 'GAMES_FETCHED',
  GAME_CREATED: 'GAME_CREATED',
  GAME_JOINED: 'GAME_JOINED',
  POSITION_UPDATED: 'POSITION_UPDATED'
}