export const gridTypes = {
  GRID_LOADED: 'GRID_LOADED',
  CELL_SELECTED: 'CELL_SELECTED',
  CELL_VALUE_CHANGED: 'CELL_VALUE_CHANGED',
  TOGGLE_DIRECTION: 'TOGGLE_DIRECTION',
  CHECK_ANSWER: 'CHECK_ANSWER',
  REVEAL_ANSWER: 'REVEAL_ANSWER',
  CHECK_SQUARE: 'CHECK_SQUARE',
  CHECK_WORD: 'CHECK_WORD',
  CHECK_PUZZLE: 'CHECK_PUZZLE',
  REVEAL_SQUARE: 'REVEAL_SQUARE',
  REVEAL_WORD: 'REVEAL_WORD',
  REVEAL_PUZZLE: 'REVEAL_PUZZLE'
}