export const puzzleTypes = {
  PUZZLE_PARSED: 'PUZZLE_PARSED',
  PUZZLE_PARSING: 'PUZZLE_PARSING',
  CELL_VALUE_CHANGED: 'CELL_VALUE_CHANGED',
  CHECK_ANSWER: 'CHECK_ANSWER',
  REVEAL_ANSWER: 'REVEAL_ANSWER'
}