export const sharedGameTypes = {
  CREATE_GAME_REQUEST: 'CREATE_GAME_REQUEST',
  CREATE_GAME_SUCCESS: 'CREATE_GAME_SUCCESS',
  CREATE_GAME_ERROR: 'CREATE_GAME_ERROR',
  GET_GAME_REQUEST: 'GET_GAME_REQUEST',
  GET_GAME_SUCCESS: 'GET_GAME_SUCCESS',
  GET_GAME_ERROR: 'GET_GAME_ERROR',
  SHARED_GAME_POSITION_UPDATE: 'SHARED_GAME_POSITION_UPDATE'
}