export const statusTypes = {
  MARK_COMPLETED: "MARK_COMPLETED",
  UNMARK_COMPLETED: "UNMARK_COMPLETED",
  MARK_SOLVED: "MARK_SOLVED",
  SAVE_TIMER: "SAVE_TIMER",
  TOGGLE_PAUSED: "TOGGLE_PAUSED",
  TOGGLE_REBUS: "TOGGLE_REBUS",
  RESET_STATE: "RESET_STATE",
  CELL_SELECTED: 'CELL_SELECTED',
  TOGGLE_DIRECTION: 'TOGGLE_DIRECTION',
  DISMISS_ALL_MODALS: 'DISMISS_ALL_MODALS'
};
