export const userTypes = {
  GAME_FETCH_REQUEST: 'GAME_FETCH_REQUEST',
  GAME_SAVED: 'GAME_SAVED',
  GAME_FETCHED: 'GAME_FETCHED',
  GAMES_FETCHED: 'GAMES_FETCHED',
  GAME_FETCH_FAILURE: 'GAME_FETCH_FAILURE'
}